name: simple_bg_location
description: A simple background location plugin for Flutter. This plugin provides a cross-platform(iOS, Android) Api for generic location functions.
version: 1.0.0
repository: https://github.com/royer/simple_bg_location
issue_tracker: https://github.com/royer/simple_bg_location/issues

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.4
  flutter_plugin_android_lifecycle: ^2.0.9
  collection: ^1.17.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.royzed.simple_bg_location
        pluginClass: SimpleBgLocationPlugin
      ios:
        pluginClass: SimpleBgLocationPlugin
